language: node_js
node_js:
  - 0.10
before_install:
  - sudo rpm -ivh http://r2space.github.io/SmartPackage/DA-SmartPackage-repository-1-0.x86_64.rpm
  - sudo yum install DA-mecab
  - sudo yum install DA-mecab-naist-jdic
